dataset_name: "temp"
aug_dataset_name: "None"
model_name: "UNETR"
model_parameters: {
  "in_channels": 10,
  "out_channels": 10,
  "img_size_w": 320,
  "img_size_h": 336,
  "patch_size": 16,
  "decoder_dim": 768,
  "masking_ratio": 0.75
}
training_parameters: {
  "learning_rate": 0.0005,
  "optimizer": "AdamW",
  "warmup_epochs": 50,
  "activation": "TanH",
  "loss_fn": "DiceCELoss",
  "dropout": 0.2,
  "num_epochs": 200,
  "batch_size": 1,
  "lambda": 1,
  "lr_scheduler": "LinearWarmupCosineAnnealingLR",
  "augmentation": "None",
  "weight_decay": 0.05,
  "aug_batch_size": 0
}
wandb: {
  "project": "TestingVideoVersions",
  "config": {
        "DATASET": "NerveDataset",
        "MODEL": "UNETR",
        "LEARNING_RATE": 0.0005,
        "WARMUP_EPOCHS": 50,
        "OPTIMIZER": "AdamW",
        "BATCH_SIZE": "1",
        "LOSS_FN": "DiceCELoss",
        "IMG_SIZE": "(320, 336)",
        "IN_CHANNELS": 1,
        "PATCH_SIZE": 16,
        "DECODER_DIM": 768,
        "MASKING_RATIO": 0.75,
        "OUT_CHANNELS": 1,
        "LAMBDA": 1,
        "NUM_EPOCHS": 200,
        "SCHEDULER": "LinearWarmupCosineAnnealingLR",
        "WEIGHT_DECAY": 0.05
        },
  "run_name": "Attempts..."
}
