train_dir: 
test_dir:
dataset_name: 
model_dir: 
model_name: 
device:
log:
test_or_train:
model_parameters: {
  "num_classes":
  "in_channels":
  "depth": 
  "seed_filters":
}
training_parameters: {
  "train_val_split":
  "learning_rate":
  "optimizer":
  "activation":
  "loss_fn":
  "dropout":
  "num_epochs":
  "batch_size":
}
testing_parameters: {
  "model_path":
  "loss_fn":
  "metric":
}
save_model: {
  "save":
  "model_name":
}
wandb: {
  "project":
  "entity":
  "config":
  "fields":
}









