dataset_name: "MallesNet"
model_name: "JointModel"
device: "cuda:0"
log: True
test_or_train: True
model_parameters: {
  "in_channels": 1,
  "out_channels": 1,
  "img_size": 256,
  "patch_size": 16,
  "decoder_dim": 786,
  "masking_ratio": 0.75
}
training_parameters: {
  "train_val_split": 0.8,
  "learning_rate": 0.0001,
  "optimizer": "AdamW",
  "activation": "ReLU",
  "loss_fn": "DiceCELoss",
  "dropout": 0,
  "num_epochs": 500,
  "batch_size": 8,
  "lambda": 1
}
testing_parameters: {
  "model_path": "../saved_models/joint-learning1.pth",
  "loss_fn":,
  "metric":,
  "save":,
  "data":
}
save_model: {
  "save": True,
  "model_name":"joint-learning1.pth",
}
wandb: {
  "project": "joint-learning",
  "fields":["train_loss", "val_loss"],
  "name": "JointLearning-MallesNet-500epochs"
}
