dataset_name: "MallesNet"
model_name: "UNETR"
device: "cuda:0"
log: False
test_or_train: False
model_parameters: {
  "in_channels": 1,
  "out_channels": 1,
  "img_size": 256,
  "feature_size": 32,
  "hidden_size": 768,
  "mlp_dim": 3072,
  "num_heads": 12,
  "pos_embed": "conv",
  "norm_name": "batch",
  "conv_block": True,
  "res_block": True,
  "dropout_rate": 0.0,
  "spatial_dims": 2
}
training_parameters: {
  "train_val_split": 0.8,
  "learning_rate": 0.001,
  "optimizer": "Adam",
  "activation": "ReLU",
  "loss_fn": "MSELoss",
  "dropout": 0,
  "num_epochs": 250,
  "batch_size": 1,
}
testing_parameters: {
  "model_path": "../saved_models/unetr1.pth",
  "loss_fn":,
  "metric":,
  "save": True,
  "data": "test"
}
save_model: {
  "save": False,
  "model_name":"unetr1.pth",
}
wandb: {
  "project": "unetr1",
  "fields":["train_loss", "val_loss"],
  "name": "UNETR-MallesNet-250epochs"
}

